### ISSUE TITLE
question

### ISSUE THREAD

**Issue by dimiy** [DreamingRaven/nemesyst#116]
Hi
do you have email?
I want to ask some things

**Comment by DreamingRaven** [comment]
Hey @dimiy 

Apologies for the late reply. Preferably id like to use github issues as it keeps everything in one place and lets others see any questions and potential solutions we might refer to.

But if its security question related or anything sensitive, you can always find my email permenantley updated here: https://github.com/DreamingRaven/nemesyst/blob/ce44b23f0ee4ba50944caa8c68f83059b6de5b1a/.arch/PKGBUILD#L6

**Comment by DreamingRaven** [comment]
Hey @dimiy since it has been a while I will close this issue. My email is there if you still want it. Happy computing.
